# Generated by Django 3.2.8 on 2021-10-24 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20211024_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyform',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='propertyform',
            name='guest',
            field=models.DateField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
