# Generated by Django 3.2.8 on 2021-10-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20211024_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
